server:
  port: 9002
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #单机版Nginx
        #server-addr: 127.0.0.1:80 #集群版
management:
  endpoints:
    web:
      exposure:
        include: "*"
