server:
  port: 7002

#eureka:
#  instance:
#    hostname: localhost #eureka 服务端的实例名称
#  client:
#    # false 表示不向注册中心注册自己
#    register-with-eureka: false
#    # 表示自己就是注册中心
#    fetch-registry: false
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#集群版
eureka:
  instance:
    # eureka 实例名称
    hostname: eureka7002.com
  client:
    # 不向注册中心注册自己
    register-with-eureka: false
    # 表示自己就是注册中心
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
