server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  zipkin:
      base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率值介于 0 到 1 之间，1 则表示全部采集 一般为0.5
      probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: liao

eureka:
  client:
    # 表示自己是否注册进EurekaServer 默认true
    register-with-eureka: true
    # 是否从 Eureka 抓取注册信息 默认为 true 单节点无所谓 集群必须设置为 true 才能配合 ribbon 使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
      # 集群版
      # defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    # 服务名称的修改
    instance-id: payment8001
    # 访问路径显示IP
    prefer-ip-address: true
    # 向服务端发送心跳的间隔 默认30秒
    lease-renewal-interval-in-seconds: 1
    # Eureka 服务端在收到最后一次心跳后的等待时间上限 单位为90 秒
    lease-expiration-duration-in-seconds: 2



mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.liao.entity #所Entity别客类所查创



